---
# - hosts: all
#   gather_facts: yes
#   vars:
#     distribution: "{{ hostvars[inventory_hostname].ansible_distribution }}"
#     release: "{{ hostvars[inventory_hostname].ansible_distribution_release }}"
#   roles:
#     - { role: bootstrap, tags: [ 'init', 'install', 'masters', 'dc', 'fileserver' ] }

- hosts: all
  gather_facts: yes
  roles:
    - { role: samba4/install, tags: [ 'install', 'masters', 'dc', 'fileserver' ] }

# - hosts: masters
#   gather_facts: yes
#   roles:
#     - { role: samba4/domain/provision, tags: [ 'provision', 'masters' ] }

# - hosts: masters:dc
#   gather_facts: yes
#   roles:
#     - { role: samba4/dns_backend/bind9, tags: [ 'dns', 'masters', 'dc' ] }

# - hosts: dc:fileserver
#   gather_facts: yes
#   roles:
#     - { role: samba4/domain/join, tags: [ 'join', 'dc', fileserver ] }

# - hosts: all
#   gather_facts: yes
#   roles:  
#     - { role: samba4/ntp, tags: [ 'ntp', 'dc', 'masters', 'fileserver' ] }

# - hosts: masters:dc
#   gather_facts: yes
#   tasks:
#     - name: Enable and start service Gluster
#       systemd:
#         name: glusterd.service
#         enabled: yes
#         state: started
#       when: sysvol_replication is defined
#   tags: [ 'masters', 'dc', 'sysvol']

# - hosts: masters:dc
#   gather_facts: yes
#   roles:
#     - { role: samba4/domain/sysvol, tags: [ 'sysvol', 'masters', 'dc' ], when: sysvol_replication is defined }

# - hosts: dc
#   gather_facts: yes
#   roles:
#     - { role: samba4/fileserver/dc, tags: [ 'fileserver', 'dc' ] }

# - hosts: fileserver
#   gather_facts: yes
#   roles:
#     - { role: samba4/fileserver/member, tags: [ 'fileserver' ] }

# - hosts: all
#   gather_facts: yes
#   roles:
#     - { role: samba4/audit, tags: [ 'audit', 'masters', 'dc', 'fileserver' ] }

# - hosts: masters
#   gather_facts: yes
#   roles:
#     - { role: samba4/configuration/dns, tags: [ 'configs_dns', 'masters' ] }
#     - { role: samba4/configuration/group_policies, tags: [ 'gpo', 'masters' ] }