---
- name: Restart NTP Chrony
  service:
    name: chrony.service
    state: restarted

- name: Enable NTP Chrony
  systemd:
    name: chrony.service
    enabled: yes

- name: Reload Daemon
  systemd:
    daemon_reload: yes

- name: Enable Samba Service
  systemd:
    name: samba.service
    enabled: yes