- name: Create smb.conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: 'smb.conf.j2', dest: '/etc/samba/smb.conf'}

- name: Winbind Create a symbolic link
  shell: |
    ln -s /usr/local/samba/lib/libnss_winbind.so.2 /lib/x86_64-linux-gnu/
    ln -s /lib/x86_64-linux-gnu/libnss_winbind.so.2 /lib/x86_64-linux-gnu/libnss_winbind.so
  ignore_errors: true

- name: Enable winbind in nsswitch.conf
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^passwd(.*)$'
    line: 'passwd:         files systemd winbind'
    backrefs: yes
  changed_when: true

- name: Reload ldconfig
  shell: ldconfig

- name: Reload Daemon
  systemd:
    daemon_reload: yes

- name: Enable winbind in nsswitch.conf
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^group(.*)$'
    line: 'group:          files systemd winbind'
    backrefs: yes