- name: Bind9 | Configure
  include_tasks: config.yml

# - name: Template a file to /etc/files.conf
#   template:
#     src: /mytemplates/foo.j2
#     dest: /etc/file.conf
#     owner: bin
#     group: wheel
#     mode: '640'