- name: Form a cluster.
  command: "gluster peer probe {{ peernode }}"
  loop: "{{ ansible_play_hosts | flatten(levels=1) }}"
  loop_control:
    loop_var: peernode
    pause: 2
  register: glusterpeerprobe
  become: true
  run_once: true
  any_errors_fatal: true
  changed_when: "'peer probe: success.' in glusterpeerprobe.stdout_lines"

- name: Configure Gluster volume.
  gluster_volume:
    state: present
    name: sysvol
    brick: /Glusterfs
    replicas: 2
    cluster: "{{ groups.all | join(',') }}"
    host: "{{ inventory_hostname }}"
    force: yes
  run_once: true
  ignore_errors: true