- name: Samba | Sysvol Replication
  include_tasks: gluster-master.yml
  when: inventory_hostname in groups.masters

- name: Samba | Sysvol Replication
  include_tasks: gluster-all.yml

- name: Samba | Sysvol Replication
  include_tasks: copy_files.yml
  when: inventory_hostname in groups.masters