- name: Create smb.conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: 'smb.conf.j2', dest: '/etc/samba/smb.conf'}
  notify:
    - Restart Samba

- name: Winbind Create a symbolic link
  shell: |
    ln -s /usr/local/samba/lib/libnss_winbind.so.2 /lib/x86_64-linux-gnu/
    ln -s /lib/x86_64-linux-gnu/libnss_winbind.so.2 /lib/x86_64-linux-gnu/libnss_winbind.so
  notify: 
    - Reload ldconfig
  ignore_errors: true

- name: Enable winbind in nsswitch.conf
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^passwd(.*)$'
    line: 'passwd:         files systemd winbind'
    backrefs: yes
  notify: 
    - Reload Daemon
    - Reload ldconfig
    - Start Samba
    - Restart Bind
  changed_when: true

- meta: flush_handlers

- name: Enable winbind in nsswitch.conf
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^group(.*)$'
    line: 'group:          files systemd winbind'
    backrefs: yes

- name: Set Domain Admins DiskOperator
  shell: 'echo "{{ admin_pass }}" | /usr/local/samba/bin/net rpc rights grant "{{ workgroup|upper }}\Domain Admins" SeDiskOperatorPrivilege -U "{{ workgroup|upper }}\administrator"'


# -  debug: msg="trigger nginx-restart"
#    notify: "Start Samba"
#    