- name: Set facts
  include_tasks: "{{ playbook_dir }}/facts.yml"
  when: fileserver.dc is defined

- name: File Server | Config
  include_tasks: config.yml
  when: fileserver.dc is defined

- name: File Server | Create Dirs
  include_tasks: create_dirs.yml
  when: fileserver.dc is defined