---

- name: Set facts
  include_tasks: ../../../../facts.yml

- set_fact:
    distribution: "{{ hostvars[inventory_hostname].ansible_distribution }}"
    release: "{{ hostvars[inventory_hostname].ansible_distribution_release }}"

- name: Samba | Configure
  include_tasks: config.yml

- name: Samba | Join
  include_tasks: join.yml

- name: Samba | Post Join
  include_tasks: post_join.yml
  when: inventory_hostname not in groups['fileserver']
