

- name: Create Backup of Idmap
  command: /usr/local/samba/bin/tdbbackup -s .bak /var/lib/samba/private/idmap.ldb
  when: inventory_hostname in groups['masters']

- name: Copy idpmap to DCs
  synchronize: src=/var/lib/samba/private/idmap.ldb.bak dest=/var/lib/samba/private/idmap.ldb
  delegate_to: '{{ groups.masters[0] }}'

- name: Flush Net Cache
  command: /usr/local/samba/bin/net cache flush
  when: inventory_hostname not in groups['fileserver']

- name: Enable and start service Bind9
  systemd:
    name: bind9
    enabled: yes
    state: started
  when: inventory_hostname not in groups['fileserver']

- name: Reset DNS Backend
  command: /usr/local/samba/sbin/samba_upgradedns --dns-backend=BIND9_DLZ
  when: inventory_hostname not in groups['fileserver']