---

- name: Remove old dir of unarchived samba
  file:
    path: "/opt/samba-{{ samba_version }}/"
    state: absent

- name: Download Samba4
  get_url:
    url: "https://download.samba.org/pub/samba/stable/samba-{{ samba_version}}.tar.gz"
    dest: /opt/

- name: Extract package in /opt/
  unarchive:
    src: "/opt/samba-{{ samba_version }}.tar.gz"
    dest: /opt/
    remote_src: true

- name: Copy fix patch Backup Offline 
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: 'domain-offline-backup.patch.j2', dest: '/opt/samba-{{ samba_version }}/domain-offline-backup.patch'}
  when: samba_version == "4.14.5"

- name: Apply fix patch Backup Offline 
  patch:
    src: "/opt/samba-{{ samba_version }}/domain-offline-backup.patch"
    basedir: "/opt/samba-{{ samba_version }}"
    strip: 1
    remote_src: yes
  when: samba_version == "4.14.5"

- name:  Compiling Samba | ./configure
  shell: ./configure --progress --enable-fhs --sysconfdir=/etc --localstatedir=/var --with-privatedir=/var/lib/samba/private --with-piddir=/var/run/samba --with-automount --datadir=/usr/share --with-lockdir=/var/run/samba --with-statedir=/var/lib/samba --with-cachedir=/var/cache/samba --with-systemd >> configure.log
  args:
    chdir: /opt/samba-{{ samba_version }}/
  when: inventory_hostname not in groups['fileserver']
  async: 1000
  poll: 0
  register: config_sleeper

- name:  Compiling Samba FileServer | ./configure
  shell: ./configure --progress --without-ad-dc --enable-fhs --sysconfdir=/etc --localstatedir=/var --with-privatedir=/var/lib/samba/private --with-piddir=/var/run/samba --with-automount --datadir=/usr/share --with-lockdir=/var/run/samba --with-statedir=/var/lib/samba --with-cachedir=/var/cache/samba --with-systemd >> configure.log
  args:
    chdir: /opt/samba-{{ samba_version }}/
  when: inventory_hostname in groups['fileserver']

- name: Compiling Samba | ./configure
  async_status:
    jid: "{{ config_sleeper.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 1000
  delay: 10

- name: Compiling Samba | make
  command: chdir=/opt/samba-{{ samba_version }}/ make -j4 make >> make.log
  async: 1000
  poll: 0
  register: make

- name: Compiling Samba | make (Please wait, this will take a while...)
  async_status:
    jid: "{{ make.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 1000
  delay: 10

- name: Compiling Samba | make install
  command: chdir=/opt/samba-{{ samba_version }}/ make install make >> make_install.log
  async: 1000
  poll: 0
  register: make_install

- name: Compiling Samba | make install (Please wait, this will take a while...)
  async_status:
    jid: "{{ make_install.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 1000
  delay: 10  