---

# - name: Copy
#   copy:
#     src: samba-{{ samba_version }}.tar.gz
#     dest: /opt/
- name: Remove old dir of unarchived samba
  file:
    path: "/opt/samba-{{ samba_version }}/"
    state: absent

- name: Download Samba4
  get_url:
    url: "https://download.samba.org/pub/samba/stable/samba-{{ samba_version}}.tar.gz"
    dest: /opt/

- name: Extract package in /opt/
  unarchive:
    src: "/opt/samba-{{ samba_version }}.tar.gz"
    dest: /opt/
    remote_src: true

- name:  Compiling Samba | ./configure
  command: chdir=/opt/samba-{{ samba_version }}/ ./configure --progress --enable-fhs --sysconfdir=/etc --localstatedir=/var --with-privatedir=/var/lib/samba/private --with-piddir=/var/run/samba --with-automount --datadir=/usr/share --with-lockdir=/var/run/samba --with-statedir=/var/lib/samba --with-cachedir=/var/cache/samba --with-systemd

- name: Compiling Samba | make
  command: chdir=/opt/samba-{{ samba_version }}/ make
  async: 1000
  poll: 0
  register: make

- name: Compiling Samba | make (Please wait, this will take a while...)
  async_status:
    jid: "{{ make.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 1000
  delay: 10

- name: Compiling Samba | make install
  command: chdir=/opt/samba-{{ samba_version }}/ make install
  async: 1000
  poll: 0
  register: make_install

- name: Compiling Samba | make install (Please wait, this will take a while...)
  async_status:
    jid: "{{ make_install.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 1000
  delay: 10