- name: Post-Install | Deploy resolv.conf template
  template:
    src: resolv.conf.j2
    dest: /etc/resolvconf/resolv.conf.d/base
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - Reload Resolvconf
    - Apply resolvconf
  when: distribution == "Ubuntu" and release == "focal"